server:
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
    username: thw
    password: thw19971017thw
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
    tomcat:
      max-active: 1000
      max-idle: 100
      min-idle: 10
      max-wait: 10000
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  activiti:
    database-schema: update
    check-process-definitions: false


mybatis:
  type-aliases-package: java.util
  mapper-locations: mapper/*Mapper.xml

