server:
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
    username: thw
    password: thw19971017thw
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.52.128.159:3306/insuranceDB
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  activiti:
    database-schema: update
    check-process-definitions: false
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: java.util

